# Download yolov3 weight, config and names files from known published locations
FROM alpine
RUN wget https://pjreddie.com/media/files/yolov3-tiny.weights && \
    wget https://raw.githubusercontent.com/pjreddie/darknet/master/cfg/yolov3.cfg && \
	wget https://raw.githubusercontent.com/pjreddie/darknet/master/data/coco.names
