# Download yolo weight, config and names files from known published locations
FROM alpine
RUN wget https://pjreddie.com/media/files/yolov2-tiny-voc.weights && \
    wget https://raw.githubusercontent.com/pjreddie/darknet/master/cfg/yolov2-tiny-voc.cfg && \
	wget https://raw.githubusercontent.com/pjreddie/darknet/master/data/voc.names


